### ISSUE TITLE
Shadow of the scroller is displayed in the property inspector when user changes its value when effect is selected. 

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1027]
1. Launch SBP.
2. Create a new project.
3. Add effect node.
4. Add glass effect.
5. Select glass effect in the property inspector.
   --Observe: Glass effect is highlighted with Purple colour in the property inspector.
6. Change any value with the scroller.
   
   -- Result: Shadow of the scroller is displayed in the property inspector when user changes it values when effect is selected. 

![shadow](https://cloud.githubusercontent.com/assets/7566802/4717895/87f1dc0a-591a-11e4-96dd-944d43681c45.png)

**Build:** SpriteBuilderPublicBeta-sb-1.3.0-beta.10-dcf-release_3.0.0-alpha.8-1796a6195bb752e59cffb5248f53ae39ca6fe441_3c4f284919369e12.dmg

MAC OS: 10.9.0
XCode: 5.0

**Comment by sana20** [comment]
This issue is still occurring.

Build: SpriteBuilder-1.3.0-rc.1
Mac OS X: 10.9.0
XCode: 5.0

**Comment by Kanoot** [comment]
This issue is reoccurring.

SpriteBuilder-1.3.4-rc.1

Device A:
Mac OS X: 10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
Found this one confusing as the steps to reproduce are different from the screenshot shown.  Please provide video.  Thanks

**Comment by khanbhai89** [comment]
What Kanoot meant here was that the scroller shadow is displayed even when we moved it, may be highlighted image will help.

![screen shot 2014-11-18 at 10 28 26 pm](https://cloud.githubusercontent.com/assets/7450007/5092659/7f445d9e-6f72-11e4-84b5-105c4de4e25f.png)

This issue is still occurring on SpriteBuilder-1.3.6.rc.1.

Mac OS X: 10.9.5.
XCode: 6.0.
