### ISSUE TITLE
The button image is not displayed only its text is displayed when the project is run on My Mac.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1130]
1. Launch Sprite Builder.
2. Make a new project.
3. Drag and drop a button on main scene.
4. Publish the project.
5. Open the project in XCode.
6. Run the project by keeping the target Project Mac > My Mac.
   
   -- Result: The button image is not displayed only its text is displayed when the project is run on My Mac.

![screenshot](https://cloud.githubusercontent.com/assets/8393830/5028577/bfb13658-6b5e-11e4-9358-6bd18c0c4b9d.png)

Build: SpriteBuilder-1.3.5-rc.2
Mac OS X: 10.9.5
XCode: 6.0

**Comment by nsluke** [comment]
Are you trying to make a game for OS X? Because it built just fine for an iPhone.
I tried recreating the results, and yes, you are correct, the button does not appear, but the console gave this message 
-[CCFileUtils fullPathForFilename:contentScale:] : cocos2d: Warning: File not found: ccbResources/ccbButtonNormal.png
Meaning it simply did not load the button image. Try adding the image file directly to your Xcode project and loading it into your CCButton through code?

**Comment by rkachowski** [comment]
Can't Reproduce

The button images appear correctly in both iOS and Mac targets on the latest version

![someting](http://puu.sh/d6adE/420d015eef.png)
