### ISSUE TITLE
SpriteBuilder folders as packages

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1200]
One of the downsides I feel is finder is a bit awkward with packages, for example look at the image.  I have hit `File/New` in Xcode to create a new Class however I am unable to easily place it in finder as Context Menu is unavailable in Finder at this point.  

I can work around it selecting the 'Group' below however it's not ideal.

Appreciate we probably can't have it all ways however want to raise for discussion.

![screenshot 2014-12-04 12 22 24](https://cloud.githubusercontent.com/assets/928115/5299420/127b6a32-7bbf-11e4-85df-a1ac84e08cfd.png)

**Comment by rkachowski** [comment]
@vlidholt mentioned this issue in the morning. After some investigation it doesn't look like it's possible to fix this issue via xcode file templates (setting a default destination inside the source directory, instead of the top level)

It seems to be a bug in Finder itself, as if you select the "List View" option in the top, instead of the "Column View" you have selected in the screenshot then you can navigate through the project. See the attached gif for illustration
![selection](https://cloud.githubusercontent.com/assets/85586/5350017/9e204e18-7ef3-11e4-8178-44f084914352.gif)
