### ISSUE TITLE
Timeline node tree in wrong order

### ISSUE THREAD

**Issue by collidernyc** [spritebuilder/SpriteBuilder#1247]
Issue was brought up here: http://forum.spritebuilder.com/t/timeline-node-tree-upside-down/2588

The timeline should order nodes from topmost highest zOrder to bottom lowest zOrder. This becomes most evident when adding a child to a parent. As an example adding a drop shadow. Almost always you would want the default to add the child behind the parent, not the other way around. Conceptually it makes no sense to have the item highest in the timeline be lowest in zOrder. All other editing programs work this way: After Effects, Photoshop, Flash, Unity etc...

**Comment by stuartcarnie** [comment]
@cocojoe – I've fixed this, as it bothers me too :)  Just playing around and then I'll push

**Comment by cocojoe** [comment]
@stuartcarnie How does it effect existing projects ?

**Comment by stuartcarnie** [comment]
@cocojoe it's only sorting visually, so it doesn't affect project structure. I was contemplating making it an option in preferences, so users used to the current order can keep it.

**Comment by collidernyc** [comment]
Thanks a ton Stuart!

**Comment by NickyWeber** [comment]
It's a matter of perspective. I like the idea of having an option to gave both ways to organize your scene.

**Comment by stuartcarnie** [comment]
Totally agree, @NickyWeber – hence the reason I opted for the preference to be set and left the default as is, to avoid confusion

**Comment by vlidholt** [comment]
I'm happy to just change this one (without any prefs), lots of people have expressed their confusion around it so I think it's the right thing to do!

**Comment by stuartcarnie** [comment]
If that is the vote, let me know and I can change it

**Comment by collinjackson** [comment]
sounds fine to me

**Comment by collidernyc** [comment]
Heh, I just wrote up a huge post with an ascii visual representation backing up a reason to have a pref, and realized Viktor is correct - it's not needed :) My vote is to just change it as well. Thanks guys!

**Comment by LearnCocos2D** [comment]
I strongly disagree. The order is perfectly fine. Most 2D game editors use a z-order based list where the topmost item is the first to be drawn (ie background).

If you come from a graphic design background (ie Photoshop) I understand that you'll see it differently. ;)
I'm well aware this is a subjective thing. I'm just surprised no one has yet spoken out **against** making this change.

The way things are (were, actually) presented are most natural as they occur in code. Basically it represents the indexes in the children array. Reversing that and you'll now have to remember that code sorts the nodes in reverse order so the problem doesn't go away, it's just shifted AND requires everyone to consider this (ie we now have a timeline vs children array sort order mismatch by default).

But, most importantly, **this change voids large parts of the Learn SpriteBuilder book (!)** and without having any data I'm pretty darn sure it goes against the gut feeling of the large majority of 2D game developers, specifically those with a programming background.

Also, Unity GUI editor has it the same way as SB used to have it before this change.
![screen shot 2015-02-05 at 13 08 09](https://cloud.githubusercontent.com/assets/214599/6061024/0fb1c5ec-ad44-11e4-8cc2-73f19df7546c.png)

So this **has to be a user-preference option** accessible from within the Project Settings dialog and **the default ought to be what it was before** if we don't want to alienate LSB readers as well as existing SB users (starting a new project). 

This is a subjective topic, so please please leave it what it was (rather: reverse it asap) but allow users to change the behavior if they really, badly want to do so but give them the option to do that from within SB (otherwise that feature might as well not exist at all).

**Comment by LearnCocos2D** [comment]
Neither:
`defaults write SpriteBuilder SEQUENCER_NODE_SORT_ORDER_REVERSE YES`

nor:
`defaults write SpriteBuilder SEQUENCER_NODE_SORT_ORDER_REVERSE NO`

changes the draw order in an existing project in SB v1.4.7 (app store build). Of course with restarts in between.
