### ISSUE TITLE
The image or node vanishes when user adds lightening effect on it.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1252]
1. Launch spritebuilder.
2. Make a project.
3. Add effect node to the ccnode.
4. Add an image under the effect node.
5. Now add the lightening effect in the effect node.
   
   -- Result: The image or node vanishes when user adds lightening effect on it.

Video Link: https://drive.google.com/file/d/0B23s5OMd3iivODJkSjNraG9RWlk/view?usp=sharing
Project Link:  https://drive.google.com/file/d/0B23s5OMd3iivdy1OM2ZyQWNaUkE/view?usp=sharing
SpriteBuilder Version: 1.4.0-beta.3
XCode: 6.1
Mac OS: 10.10.1

**Comment by thayerandrews** [comment]
I've submitted pull request https://github.com/cocos2d/cocos2d-swift/pull/1143 that addresses this issue. It should be noted however that even with this fix, CCEffectLighting is not completely compatible with CCEffectNode since there is no way to specify a normal map with this combination of effect and node.

**Comment by sana20** [comment]
This issue is fixed.

SpriteBuilder-1.4.7 
Mac OS X: 10.10.1
XCode: 6.2.
