### ISSUE TITLE
Cannot navigate within project folders

### ISSUE THREAD

**Issue by mbgames** [spritebuilder/SpriteBuilder#1256]
In finder, you have to command+click and select reveal package contents to view files.  However if you try to add a new class or some other file within xCode, that option is not available, so you can't put it where you want.

Also if you want to add files to your project that are in the project direct from xCode, you cannot navigate to them.

SB Version: 1.4.0-beta.3
SB Revision: facbf2f58e

**Comment by mbgames** [comment]
Just another quick follow up here.  I just made a new project with SB.  I then published and then tried to open in XCode.  Since I can't navigate to the folder with the open dialogue box.  

To open, I have to navigate in finder, right click and "show package contents", then double click the xcode project file.  From then on I can open in xcode as a recent project.

This is quite awkward.  Not sure if this is an intentional change - but I hope not.  It's frustrating when things are hidden (like iPhoto for example - just where are my pictures actually...)

For adding files to the project from within xcode, if I select a sub folder, then file-new, I can navigate the directory to put the new file where I want, but if I have the top level node selected then I can't.

The project folders show up as red, so they must be some sort of system recognized things, but I don't know what that is.

SB Version: 1.4.0-beta.3
SB Revision: facbf2f58e

**Comment by collinjackson** [comment]
My suggestion would be for SpriteBuilder to not add an extension to the directory it creates when a new project is created. You could still launch SpriteBuilder by clicking the ccbproj file inside the folder, but it would make it easier to get to the Xcode project if you didn't know the keyboard shortcut for it. (As an aside, I think we should use the extension sbproj instead of ccbproj, although we can register for both extensions for backwards compatibility purposes)

**Comment by csmillie** [comment]
Agreed.  One of the first things I did with my SB project was to remove the extension on the directory so that I could navigate to files from inside of Xcode and other interfaces where the "Show Package Contents" option is not available..

**Comment by cocojoe** [comment]
Related #1200, agree on removing extension, anything that obfuscates navigation is annoying.

**Comment by cocojoe** [comment]
If we are going to start refactoring the cocosbuilder project extension, shouldn't we look at doing this across the board?

**Comment by collinjackson** [comment]
Yes! I have some ideas about that, which I'll share with you. It's out of scope for this GitHub issue.

**Comment by NickyWeber** [comment]
I totally agree that navigation is very important. The main reason for this change was issue with opening a project file by double clicking is the sandbox. People ran into issues because certain files could not be accessed. Opening a project by opening the whole project folder ensures access to all files contained. Same issue with packages, although packages don't contain source code files. 

I am uncertain how to solve this properly. We don't have a file access layer in place that can actually ask for the user's consent if access is prohibited. This would make things easier but would cause open file dialogs popping up whenever there is a need for a permission.

A first step could be to remove the .spritebuilder extension again and make people open project within SB by using the Main Menu > File > etc. So we get around the navigation issues. 

See this issue: https://github.com/spritebuilder/SpriteBuilder/issues/1168. This is more of an example of what can happen if a ccbfile is opened by double clicking and not having access to alle files.

**Comment by collinjackson** [comment]
I spent some time talking to Vik about this and we came up with several solutions. I think we are in agreement that we should remove the .spritebuilder extension from the main folder, the only question is how to get the sandbox to do what we want.
1. Our suggested approach: When the user opens the project by double-clicking the .ccbproj file, we attempt to access the Source and Packages folders. If we discover that we do not have access to these folders, we open a file dialog pointing to the parent folder of the .ccbproj and if the user clicks open, then we'll have access. If they dismiss the open dialog, the project does not open and no error is shown. In the common case where the project was created/opened by the user with SpriteBuilder previously, everything will work seamlessly, and in the unusual case where they're opening a project from someone else, it's just one more click. I don't think an explanation dialog is necessary as it's pretty obvious what the user needs to do.
2. Alternative approach we considered: Change the Source and Packages folders to ProjectName.source and ProjectName.packages. This will cause the sandbox to treat them as [related files](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW22). However, changing the project layouts would make upgrading more complicated.

There are some variations on the second option that would allow the project layouts to remain the same using soft links. However, soft links can be confusing.

**Comment by NickyWeber** [comment]
@collinjackson Nice, I talked to cocojoa today and suggested something like 1. I suggest to show the open dialogue all the time since it's pretty hard to tell which file/folder could be restricted within the project folder. This solution should be easily done and I am already working on it.

**Comment by collinjackson** [comment]
@NickyWeber it seems like [security-scoped bookmarks API](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16) are the recommended way to request permanent access to a file and later determine whether the bookmark is stale or not.

**Comment by NickyWeber** [comment]
@collinjackson I experimented with them already in a different case, they cannot be used for directories. Access to the project folder is the best way to ensure read and write privileges for anything contained.

**Comment by collinjackson** [comment]
App scoped bookmarks can refer to a folder.

**Comment by NickyWeber** [comment]
@collinjackson You are right, I was missing something, although an error stated just that. I added the bookmarks in my pull request.

**Comment by cocojoe** [comment]
Are we happy to merge pull? The user experience seems fine to me, the only issue is the icon however can certainly live with that for now if we need to get 1.4 out the door.
