### ISSUE TITLE
Application crashes when user tries to add Refraction effect on an image.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1387]
1. Launch Application.
2. Drag and image named "bush.png" in resource view.
3. Drag and Drop it into MainScene.ccb.
4. Try to effect refraction onto it by property view.
   
   -- Result: Application crashes to the Mac OS X.

You can find the video here: https://drive.google.com/file/d/0B5KeRaV3CWUab0k5RmxQaVh5SVU/view?usp=sharing

 This happened 3/3 times.

Build: SpriteBuilder-1.4.8-rc.0.zip

Mac OS X: 10.9.5.
XCode:  6.1.

**Comment by thayerandrews** [comment]
I've been digging into this one a bit and here is some relevant information:
- The crash is caused by an "unrecognized selector sent to instance" exception when "plugIn" is called on CCBPEffectRefraction.
- "plugIn" is called on CCBPEffectRefraction during NIB loading for InspectorNodeReference when InspectorValue tries to determine if it is readonly. This code references selection.plugIn and selection is a CCBPEffectRefraction which triggers the offending call.
- This affects all effect classes that use InspectorNodeReference (reflection, refraction, glass).
- This problem was uncovered by d0a4daabd585d252abd50d396a33ff63969b97eb but it only exposes the bug, it is not the cause of it.
- The fundamental problem is that InspectorValue is designed to be used with selections that are subclasses of CCNode but, in the case of effects editing and InspectorNodeReference, InspectorValue being used with CCEffects which do not derive from CCNode. The problematic code can be found here: 
  https://github.com/spritebuilder/SpriteBuilder/blob/v1.4/SpriteBuilder/ccBuilder/EffectRefractionControl.m#L44
- The temporary fix is to add a plugIn method to reflection, refraction, and glass that returns nil.
- The long term fix is to either rework effects editing to not use InspectorValue or rework InspectorValue so it can be used with classes that are not derived from CCNode.

**Comment by sana20** [comment]
This issue is also happening when user adds glass or reflection effect as well.

Version: SB 1.4.8-rc.0 with SBAndroidPluginProfessional-b8ffe603
Mac OS X: 10.10.1
XCode: 6.1.

**Comment by sana20** [comment]
This issue is fixed.

SpriteBuilder Version -1.4.7
Mac OS X: 10.10.
XCode: 6.2.

**Comment by NoorFatima** [comment]
This issue is re-occurring. This issue is also occurring for Glass effect and Reflection effect.

Mac OS X: 10.9.5
XCode: 6.1
SB Version: 2.0.0
SB Revision: 4fd68fb

**Comment by Shahidwerplay** [comment]
This issue is re-occurring. This also is also occurring for Glass effect and Reflection effect.

SB Version: Latest Develop Branch (2.0)
SB Revision: 02eedd13c8
Mac OS 10.10.0
XCode 6.1
