### ISSUE TITLE
Check when opening old files

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1472]
Make a check and warn the user if hen is opening an old SpriteBuilder 1.x file. Possibly make an migration guide.

**Comment by NickyWeber** [comment]
This should be fixed by my pull request: https://github.com/spritebuilder/SpriteBuilder/pull/1464.

You can always look at a log file for more information especially in case something goes wrong.

![bildschirmfoto 2015-04-02 um 10 30 56](https://cloud.githubusercontent.com/assets/5259653/6960518/7e43bca8-d923-11e4-9f5a-1342876021bc.png)

![bildschirmfoto 2015-04-02 um 10 31 36](https://cloud.githubusercontent.com/assets/5259653/6960522/81e288f8-d923-11e4-8981-279d7af0c589.png)

**Comment by rkachowski** [comment]
This is available in current develop
