### ISSUE TITLE
Publishing pvr / jpg images needs to be testing with new publisher

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1527]
Publishing per and jpg images needs to be tested so that they work correctly with the new publisher and Cocos2D. Possible multiple images of these may need to be saved, or mip map for pvr textures enabled.

**Comment by slembcke** [comment]
Subtasks:
1. Switch from `.ccz` to regular `.gz`. **
2. Add a parameter to `[FCFormatConverter convertImageAtPath:...]` to specify if the image is untagged. Generating the mipmaps looks to  be as simple as calling `pvrtexture::GenerateMIPMaps()`.
3. JPEG seems to work fine. Was this just to test loading untagged JPEGs in Cocos2D?

*\* The existing performance problems with `.gz` files should be fixed and `.ccz` files are now loaded as `.gz` files by skipping the first few bytes.

**Comment by slembcke** [comment]
1 is done. 2 is sort of done, but there is no way to invoke it since you can't specify automatically scaled assets through the UI yet. I could only test it by hardcoding it to be be enabled. Check https://github.com/spritebuilder/SpriteBuilder/pull/1574

3 doesn't work after all. I loaded the JPEG file directly instead of using the aliased name or letting a CCB file load it. We need to implement the metadata export since that is where the aliased filenames are stored now.

**Comment by slembcke** [comment]
Filename aliases are now implemented: https://github.com/spritebuilder/SpriteBuilder/pull/1574
