### ISSUE TITLE
CCButton: Background Color is ignored

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#181]
No matter if I set the sprite frame to null or not, the background color for the button is gonored. Here is the button on a yellow stage:
![bildschirmfoto 2014-01-15 um 17 39 06](https://f.cloud.github.com/assets/695826/1922193/99bc3f36-7e03-11e3-8203-4c62cb0b2d6d.png)

And here are the properties:
![bildschirmfoto 2014-01-15 um 17 36 23](https://f.cloud.github.com/assets/695826/1922172/4bdac7d8-7e03-11e3-8b4f-e96feda82e9a.png)

**Comment by jtwigg** [comment]
That seems to make sense to me at the moment since, as you don't have a background image to colorize, then your Background Colour is being applied to nothing.

Here's me using a white_square.png background image (its a white square) and coloring it red. 
The stage is a blue stage.
The Label colour is blue.

![screen shot 2014-01-15 at 12 28 50 pm](https://f.cloud.github.com/assets/1237233/1924558/f2660444-7e23-11e3-820f-69af1d43c617.png)

![screen shot 2014-01-15 at 12 29 02 pm](https://f.cloud.github.com/assets/1237233/1924562/0013c482-7e24-11e3-8ba9-7581dcda563d.png)

**Comment by jtwigg** [comment]
Would like to close. Will reopen if further issues.

**Comment by jan-happy** [comment]
Thanks again for the workaround, although I think it would make sense that a CCButton would not need a bitmap resource and can just have a background color.

**Comment by jtwigg** [comment]
I agree. I also think people will more likely want beveled and rounded edges , which is when they'd use 9 slices. It'd be nice to support the full range of background experiences: Solid color & Image

Will add request.

**Comment by jan-happy** [comment]
Thank you!
