### ISSUE TITLE
SpriteBuilder crashes when publishing this project

### ISSUE THREAD

**Issue by Ben-G** [spritebuilder/SpriteBuilder#199]
https://github.com/MakeGamesWithUs/Spritebuilder-Getting-Started/commit/f6b7cd4c47022201918bb88e86a5ae2e33d5bb85

Unfortunately I don't know the exact reason. Only hint: I have copied a lot of keyframes / timeline animations in this project.

**Comment by jtwigg** [comment]
okay. I'll take a look see.

**Comment by jtwigg** [comment]
I can see what the problem is: One of your penguins, the third CCBFile in Timeline: LaunchPenguin2 is broken. 
His visibility keyframes seems to be corrupt. Im going through all the ways it could get corrupt, and found one (shortening the timeline past that visibility keyframe).

To fix the corruption, add back in a visible keyframe, and delete it again, and it will clean itself up properly.

**Comment by jtwigg** [comment]
This should no longer happen in the latest, however files that are corrupted will remain corrupted.
If its a problem, I can put in a fixup for others.

**Comment by Ben-G** [comment]
> and found one (shortening the timeline past that visibility keyframe).

Yep, I did that, so that must have caused the crash. Thanks for fast response & fix.
