### ISSUE TITLE
CCLabelTTF - Outline effect always black when build in XCode

### ISSUE THREAD

**Issue by lagmacstudio** [spritebuilder/SpriteBuilder#271]
If you sets a color for the outline effect, in SpriteBuilder you can see the right color but when build the project in Xcode the color is always black.

**Comment by vlidholt** [comment]
https://github.com/cocos2d/cocos2d-iphone/pull/667 attempted to fix this but introduced another issue. This commit may need to be reversed as the old solution (which works on iOS 6 but not 7) is probably closer to a correct solution.

Image below illustrates the current issue.

![fonts2](https://cloud.githubusercontent.com/assets/1539812/2598154/3c406c70-bac0-11e3-97a5-bc41384778ef.png)

**Comment by NickyWeber** [comment]
This behaviour was not introduced with this patch, it existed before in cocos2d. 

A screenshot of a cocos2d version without the patch, showed in 6.1, 7.0 and 7.1.

![bildschirmfoto-2014-04-04-um-11 06 43](https://cloud.githubusercontent.com/assets/5259653/2613725/3d5710ca-bbdb-11e3-8537-46dbc75fd63d.png)

I filed a pull request on cocos2d which should fix this.
https://github.com/cocos2d/cocos2d-iphone/pull/679 

Ths problem was the second draw of the stroke/outline to cover the shadow glitches, it had no impact due to a wrong text drawing mode.

**Comment by vlidholt** [comment]
Fixed, closing this one! :)
