### ISSUE TITLE
Move build warnings to tab on the left side

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#44]
The current pop-up is somewhat confusing (some click it instead of the build button). Make the build button nicer looking and a bit bigger, and move the warnings to it's own tab on the left hand side (similar to how Xcode works).

**Comment by jtwigg** [comment]
![screen shot 2013-11-13 at 1 20 13 pm](https://f.cloud.github.com/assets/1237233/1535842/8bde826a-4ca9-11e3-8671-ae76e77063c9.png)

Here's the current work in progress. I'm wondering how deep to take the cell's of the outlineView. Right now they're just text. Things that could be added.

a) Icon's displaying FATAL or not
b) If they refer to a file, list the file and if you double click, goto the file
c) catagorize by file allowing it to expand on a particular files warnings.

**Comment by vlidholt** [comment]
Looking good! For the coming release, what would be nice are:

1) Warning icons next to the messages (fatal or not is not super important, but if it's easy to add that would be cool)
2) Right after publishing (only if there are any warnings) switch to the warnings tab so they get visible.

The other ones would be really nice additions, but has lower priority. We could save them for 1.1 or if we get time left after the other issues are done.

**Comment by jtwigg** [comment]
Todo: Also test dirty'ing the filedate if there's warnings.

**Comment by jtwigg** [comment]
FIXED

**Comment by jtwigg** [comment]
1) The focus ring needs to go. If you override CCBTableView/CCBOutlineView instead of a regular table view this should work (this can be changed in the xib file).
2) We need some line breaks in there (cells should expand if they are multiple lines)
3) Use the editor-warning.png image for the warnings.
4) If nothing can be done with the rows, they shouldn’t be selectable. (For the future we may want to enable selections again at some point)
5) Looks like it’s pushed to the right a little bit. Is this because you used an outline view? If so, maybe we can just move it a couple of pixels offscreen on the left hand side until we implement the folding out arrows?

**Comment by jtwigg** [comment]
6) Should implement copy paste to clipboard?

**Comment by jtwigg** [comment]
1) Fixed
2) I've put in Mouse Hover overlays.
3) Fixed
4) Copy paste overrides this.
5) Fixed
6) Fixed

**Comment by vlidholt** [comment]
Good enough for 1.0 release. Things to fix for 1.1:
1. Nicer looking selections
2. Smaller font (that matches other list fonts)
3. Line breaks.

**Comment by jtwigg** [comment]
This has been refactored again.
Closing.
