### ISSUE TITLE
New CCB files takes several seconds to appear in resources list

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#458]
Creating a new CCB file takes about 3 seconds before the new file appears in the resources list. This is with the App Store build, develop builds take up to 5 seconds. "Scene" CCBs seem to take a little longer than other CCB types.

If this can't be made faster creating new CCBs ought to show a progress indicator. Generic one should suffice.

The problem (besides waiting) is mainly conditioning as you try to find ways that make the new CCB appear in the list (faster). I got into the habit of double-clicking another CCB which seemed to make the new CCB appear faster, so I kept doing that - but alas that was a false observation. You just have to wait.

**Comment by cocojoe** [comment]
Yeah, I just thought maybe my machine was slow the first few times, agree a visual indicator would be nice as imagine quite a few people think 'is this working...' the first few times.

**Comment by NickyWeber** [comment]
Question is: why does it take so long?

**Comment by LearnCocos2D** [comment]
Judging from the log there's a lot of resource loading going on.

**Comment by NickyWeber** [comment]
The delay comes from pathWatcher ivar in ResourceManager.m. It is a SCEvents and used to track changes to the file dir. There is a latency property to bundle events. Default is 3.0 which can sometimes hit hard. This can be solved by adding `pathWatcher.notificationLatency = 0.1;` to ResourceManagers init method. 

The file is written quite quickly. There is some heavy load in the code due to generating the preview and cascading reloading actions. Still this should be quick enough, however the file system is monitored as mentioned above and updates come from the observer.

Another solution could be to add a method or make a private on public in the ResourceManager to update the dir directly in which the new ccb exists.

**Comment by vlidholt** [comment]
I think the best solution would be to have the resource manager update the dir directory in which the new ccb exists. It's probably not more than a line of code (in the right place).
