### ISSUE TITLE
French text is not displayed on stage when user changed language from english to french.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#488]
Description:
1. Add CCLabelTTF to the stage.  Enter "Sample Text" into label text.
2. Check localize.
3. Click Edit.
4. Add second language of French.
5. Enter text for French. (Exemple de Texte)
6. Exit to Stage.

 -- Result: French text is not displayed on stage when user changed language from english to french. Screenshot is attached.
![text](https://cloud.githubusercontent.com/assets/7566802/2971127/7d541628-db66-11e3-935b-87241e86f50b.png)

 This is 3/3 times.

Build version used: SpriteBuilder-1.1.0-beta.1

Used: MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by vlidholt** [comment]
The reason the text isn't displayed is because you aren't editing the translation. Instead you are editing the key. Select the 'Sample Text' row and add a translation under the 'French' column.

I'd recommend going through a couple of tutorials, reading through the user guide and asking things in the forums so that you understand SpriteBuilder better before submitting bug reports.

**Comment by LearnCocos2D** [comment]
I have to admit, I also made this exact mistake. It took me a few tries and close look at the behavior of the dialog to understand what I'm supposed to do.
