### ISSUE TITLE
Issue with psd:s and smart sprite sheets

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#649]
See: http://forum.spritebuilder.com/t/psds-and-smart-sprite-sheets-sb-1-1-0-cocos-3-1-0/1359

**Comment by NickyWeber** [comment]
Found a quick solution for the user.

XCode runs a script everytime a project is run to publish with SB if it's among the processes. This leads to a bug: fileLookup.plist gets overwritten on a non clean publish because unchanged image files don't get into the lookup again. 

Will work on a fix.

**Comment by NickyWeber** [comment]
**Long version of this bug:**
Publishing an already published unchanged smart spritesheet(SSS) overwrote the filelookup.plist. 
The lookup is always generated from scratch. The renaming rules are created quite deep in the publishing process on a per file basis, which works for non SSS, since the operations are skipped internally. The SSS publish operations are skipped before the they are created.

**Current solution:** SSS operations now generate an intermediate filelookup stored in the particular folder which are then merged with all other renaming rules.

**Better solution, maybe some day:** Put the spritesheet generation with ALL dependencies(image processing) in one operation. Split up the image processing and generation of the renaming rules into separate operations.

Pull request is on the way. Done.
