### ISSUE TITLE
Interface does not fully support retina

### ISSUE THREAD

**Issue by jscheel** [spritebuilder/SpriteBuilder#705]
Several elements of the interface, such as the timeline, rules, and several icons are blurry on retina screens.

**Comment by NickyWeber** [comment]
You are referring to a Macbook's retina display, right?

**Comment by cocojoe** [comment]
I use a MBP 15" retina most of the time, not a big issue however could mark this as a low priority enhancement as it should be added as a matter of course.

**Comment by jscheel** [comment]
@NickyWeber yes, working on a 15" MBP.

**Comment by NickyWeber** [comment]
@cocojoe I agree, non retina here :)

**Comment by stuartcarnie** [comment]
I am working on this. I will have to make some tweaks to Cocos2D-Swift in the process. 

In addition, given normal OS X apps use the `@2x` convention, I'd am going to use that for all the assets in the GUI rather than a mixture of Cocos2D conventions (-machd and @2x).

**Comment by cocojoe** [comment]
What needs changed in Cocos2D?

**Comment by stuartcarnie** [comment]
`CCConfiguration` does not differentiate [screen devices](https://github.com/cocos2d/cocos2d-swift/blob/v3.3/cocos2d/CCConfiguration.m#L235-L238) on OS X

**Comment by cocojoe** [comment]
Thanks, can live with that :)

**Comment by stuartcarnie** [comment]
Cool. 

Spritebuilder is certainly a special case consumer of Cocos2D, given it is a desktop application, hosting Cocos2D along with a lot of native UI. With that in mind, using `-machd` for HD assets in Spritebuilder will cause friction and confusion since there will be a mixture of assets that are `@2x` (native UI) vs Cocos2d. If it can be avoided, I'll attempt to inject the `@2x` into `CCFileUtils` via existing APIs, however if I identify any problems with that approach, that class may need some minor modifications.

**Comment by cocojoe** [comment]
Do  you intend to publish your branch soon? I can test it on my MBP.

**Comment by stuartcarnie** [comment]
Taking some time to redo the assets as HD versions, so maybe another day or so and I'll push it up. 

I still have to resolve with the fact that SB uses the `contentScaleFactor` on `CCDirector` to show different device sizes / scales, but I also need to scale the UI on the Mac between retina and normal DPIs

**Comment by stuartcarnie** [comment]
@cocojoe, it's pushed up – you'll need to refer to my fork in order to use the [cocos2d-swift/retina](https://github.com/stuartcarnie/cocos2d-swift/tree/retina) branch for some minor changes

Still adding a few more icons, but it looks much better now. Also worth noting that it correctly handles dragging between screens of differing content scale factors

**Comment by cocojoe** [comment]
Thanks, can hopefully check it out today for a look.

**Comment by jscheel** [comment]
Wow, awesome! Thanks @stuartcarnie!
