### ISSUE TITLE
How can I check more than one timeline as autoplay?

### ISSUE THREAD

**Issue by Ricardo1980** [spritebuilder/SpriteBuilder#743]
Hello!
When I press "autoplay", the other timeline with autoplay is unchecked.
How can I check more than one timeline with autoplay enabled?
Thanks.

**Comment by LearnCocos2D** [comment]
There can only be one timeline playing per node, if I understand correctly. If true, it doesn't make sense to allow more than one timeline to autoplay because only one of them would be playing.

You can put everything that should autoplay in the same timeline however. Or you can design whatever you need to animate in multiple CCBs included in the "main" CCB, so each individual CCB files can create its own autoplay timeline.

**Comment by Ricardo1980** [comment]
Thanks. I created several CCB files.
