### ISSUE TITLE
Remove Android device from iOS target and vice versa

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#889]
The Android target has the option to build for iOS devices and vice versa - this should be removed so that only the relevant build option is available for each target.

**Comment by collinjackson** [comment]
Breckin told me that all we need to do to remove the iOS devices from the Android target is add Android targets to Chipmunk and Tremor. I can do this in issue #888

**Comment by breckinloggins** [comment]
Yeah, the tremor and chipmunk projects need Android targets of their own, and the cocos2d android target needs to link to them instead of the iOS targets. Once it's Android targets "all the way down", the iOS devices should disappear from the Android scheme. At least this is how it worked in my testing.

**Comment by collinjackson** [comment]
Fixed in #888
