### ISSUE TITLE
“Categories” and “Masks” are not saved (physics)

### ISSUE THREAD

**Issue by Ricardo1980** [spritebuilder/SpriteBuilder#903]
Hello!

Using SpriteBuilder 1.2.1, after a few tests I carried out, I realised very often these two values are not saved into the ccb file, so when creating the ccbi file, they are not there.
Can anyone confirm that?
Just modify the field, press SAVE ALL and then open the ccb file with a text editor to see that they are not saved.

It's a bit frustrating trying to make my collisions work under this situation.

Thanks a lot!

**Comment by cocojoe** [comment]
I've seen this happen but it happens in general in Xcode etc if you modify a field but do not change focus to complete it.  For example:

![screen shot 2014-10-08 at 11 28 27](https://cloud.githubusercontent.com/assets/928115/4557710/57359b04-4ed6-11e4-89b0-5baf821b408c.png)

If I save at this point it would not save as guessing it's not actually committed until focus change.  Ideally it should update after each keyword.

**Comment by Ricardo1980** [comment]
Nope. I tested it and if I move the focus, save all, close the CBB file and open again... I don't see the changes. Something is not working properly here but I don't know exactly what.
Can you reproduce what I say? Otherwise I can create a video or similar.

**Comment by cocojoe** [comment]
Yes I can recreate in 1.3 Beta.

When I first tested I did 'Save' and this worked fine.  However agreed if you use 'Save All' it doesn't actually save the change.

I'll flag this up.

**Comment by Ricardo1980** [comment]
Thanks.
I even created a video!
https://vimeo.com/108342993

Anyway, do you know a workaround or similar? Under several conditions is saved but I don't know them.
Maybe I have to edit the file manually.

BTW, probably this is also related:
http://forum.spritebuilder.com/t/physicsbody-collisiontype-working-but-not-from-spritebuilder/1991

**Comment by cocojoe** [comment]
Have you tried 1.3 Beta ? 

For me if I changed focus and then pressed Command+S to save, this worked fine for me.

Thanks

**Comment by Ricardo1980** [comment]
No. I only use 1.2.1 because that's the version in the App Store and it is updated automatically.

**Comment by NickyWeber** [comment]
Ok, fix ready for next release 1.3. I am uncertain if this should go into a 1.2.2 fix release, I will ask.

Thanks for the video btw.

**Some notes on this issue:**
You will have to lose focus or hit enter to apply changes in those editors mentioned above otherwise the bindings won't kick in and the model is not updated. **This cannot be fixed.**

What happened in this bug is the document was not marked as dirty therefore save all would not save the document. Funny enough the save command will always save regardless of the dirty mark. A publish will save all. As soon as you double click the ccb it is loaded from disk which lead to the reset of the values. 

Changing those three values will now mark the document as dirty and saving in the many ways there are will persist the values.
